apiVersion: v1
kind: Service
metadata:
  name: mssql-external
  labels:
    component: mssql
spec:
  type: LoadBalancer
  ports:
    - port: 1433
      targetPort: 1433
      name: TCP
  selector:
    component: mssql