apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    component: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    app: taskQueue
    component: rabbitmq