apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    component: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - port: 15672
      targetPort: 15672
      name: http
  selector:
    component: rabbitmq